services:
  keycloak:
    image: keycloak/keycloak:25.0
    container_name: keycloak
    command: start --https-certificate-file=/etc/keycloak/sso.qr.uqk.crt --https-certificate-key-file=/etc/keycloak/device.key --import-realm
    environment:
      KC_HOSTNAME: sso.qr.uqk
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 443:8443
    restart: always
    volumes:
      - ./certs/sso.qr.uqk.crt:/etc/keycloak/sso.qr.uqk.crt
      - ./certs/device.key:/etc/keycloak/device.key
      - ./realm:/opt/keycloak/data/import
    depends_on:
      - keycloak_db
    networks:
      - keycloak_net

  keycloak_db:
    image: postgres:16
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    networks:
      - keycloak_net

networks:
  keycloak_net:
    external: true
      